version: '3.8'
services:
  wordle-cache:
    image: redis:7.0.4
    ports:
      - '6380:6379'
    command: redis-server --loglevel verbose
    volumes:
      - cache:/data
volumes:
  wordle-cache:
    driver: local
